<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class CatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            ['id' => 1, 'name' => 'Salicylic Acid Daily Cleanser', 'brand' => 'COSRX', 'description' => 'A gentle BHA cleanser that controls oil and prevents breakouts without stripping the skin.', 'price' => 1299, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=400', 'rating' => 4.8, 'reviews' => 124, 'ingredients' => 'Water, Glycerin, Salicylic Acid, Tea Tree Oil', 'how_to_use' => 'Massage onto wet face, rinse thoroughly. Use AM and PM.', 'benefits' => 'Controls excess oil, clears pores, prevents acne.'],
            ['id' => 2, 'name' => 'Niacinamide 10% + Zinc 1%', 'brand' => 'The Ordinary', 'description' => 'High-strength vitamin and blemish formula to regulate sebum and minimize pores.', 'price' => 1450, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400', 'rating' => 4.9, 'reviews' => 412, 'ingredients' => 'Aqua, Niacinamide, Zinc PCA', 'how_to_use' => 'Apply to entire face morning and evening before heavier creams.', 'benefits' => 'Reduces blemishes, balances sebum activity.'],
            ['id' => 3, 'name' => 'Fit Me Matte + Poreless Foundation', 'brand' => 'Maybelline', 'description' => 'Ideal for normal to oily skin, this matte foundation controls shine and blurs pores.', 'price' => 1500, 'category' => 'makeup', 'skin_type' => 'oily', 'image' => 'https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&q=80&w=400', 'rating' => 4.7, 'reviews' => 890, 'ingredients' => 'Aqua, Cyclohexasiloxane, Nylon-12', 'how_to_use' => 'Apply evenly to face and blend with fingertips or sponge.', 'benefits' => 'Mattifies skin, refines pores, natural finish.'],
            ['id' => 4, 'name' => 'Hydrating Gentle Cleanser', 'brand' => 'CeraVe', 'description' => 'Cleanses and hydrates without disrupting the protective skin barrier. Perfect for combination skin.', 'price' => 2100, 'category' => 'skincare', 'skin_type' => 'combination', 'image' => 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=400', 'rating' => 4.8, 'reviews' => 320, 'ingredients' => 'Ceramides 1, 3, 6-II, Hyaluronic Acid', 'how_to_use' => 'Wet skin with lukewarm water. Massage cleanser into skin in a gentle, circular motion. Rinse.', 'benefits' => 'Cleanses, hydrates, restores protective skin barrier.'],
            ['id' => 5, 'name' => 'True Match Super-Blendable Foundation', 'brand' => 'L’Oréal', 'description' => 'A natural-finish foundation that adjusts to your skin tone and texture.', 'price' => 2450, 'category' => 'makeup', 'skin_type' => 'combination', 'image' => 'https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&q=80&w=400', 'rating' => 4.6, 'reviews' => 210, 'ingredients' => 'Aqua, Isododecane, Cyclopentasiloxane', 'how_to_use' => 'Dot onto face and blend outwards.', 'benefits' => 'Medium coverage, natural finish, matches undertone.'],
            ['id' => 6, 'name' => 'Hyaluronic Acid 2% + B5', 'brand' => 'The Ordinary', 'description' => 'A hydrating formula with ultra-pure, vegan hyaluronic acid.', 'price' => 1650, 'category' => 'skincare', 'skin_type' => 'dry', 'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400', 'rating' => 4.9, 'reviews' => 550, 'ingredients' => 'Aqua, Sodium Hyaluronate, Panthenol', 'how_to_use' => 'Apply a few drops to face AM and PM before creams.', 'benefits' => 'Deep hydration, plumps skin, supports skin barrier.'],
            ['id' => 7, 'name' => 'Pro Filt’r Hydrating Longwear Foundation', 'brand' => 'Fenty Beauty', 'description' => 'A hydrating, natural finish foundation that delivers comfortable, long-wear coverage.', 'price' => 5200, 'category' => 'makeup', 'skin_type' => 'dry', 'image' => 'https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&q=80&w=400', 'rating' => 4.8, 'reviews' => 310, 'ingredients' => 'Grape Seed Oil, Sodium Hyaluronate', 'how_to_use' => 'Massage tube. Squeeze a dime-size amount onto back of hand and blend onto face.', 'benefits' => 'Hydrating, medium to full coverage, natural finish.'],
            ['id' => 8, 'name' => 'Advanced Snail 96 Mucin Power Essence', 'brand' => 'COSRX', 'description' => 'Lightweight essence which absorbs into skin fast and gives skin natural glow from inside.', 'price' => 2800, 'category' => 'skincare', 'skin_type' => 'all', 'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400', 'rating' => 4.9, 'reviews' => 1250, 'ingredients' => 'Snail Secretion Filtrate, Sodium Hyaluronate', 'how_to_use' => 'After cleansing and toning, apply a small amount on your entire face.', 'benefits' => 'Repairs damaged skin, deeply hydrates.'],
            ['id' => 9, 'name' => 'Heartleaf Pore Deep Cleansing Foam', 'brand' => 'Anua', 'description' => 'Deep pore cleansing foam with Heartleaf extract to soothe and clear oily skin.', 'price' => 2150, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => '/images/skincare1.jpg', 'rating' => 4.7, 'reviews' => 215, 'ingredients' => 'Heartleaf Cordata Extract 33.4%, Quercetin 10,000ppb', 'how_to_use' => 'Lather a moderate amount with water and gently massage onto the face.', 'benefits' => 'Deeply cleanses pores, soothes troubled skin.'],
            ['id' => 10, 'name' => 'Moisturizing Lotion for Normal to Oily Skin', 'brand' => 'CeraVe', 'description' => 'Lightweight, oil-free daily moisture that provides lightweight hydration.', 'price' => 2400, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => '/images/skincare2.jpg', 'rating' => 4.8, 'reviews' => 840, 'ingredients' => 'Ceramides, Hyaluronic Acid', 'how_to_use' => 'Apply liberally as often as needed, or as directed by a physician.', 'benefits' => 'Restores skin barrier, non-comedogenic, oil-free.'],
            ['id' => 11, 'name' => 'Oil Control Moisturising Gel-Cream', 'brand' => 'CeraVe', 'description' => 'Rebalances oily skin, controls excess oil and shine while minimizing pores.', 'price' => 2800, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => '/images/skincare4.jpg', 'rating' => 4.6, 'reviews' => 312, 'ingredients' => 'Ceramides, Niacinamide, Silica', 'how_to_use' => 'Apply evenly to face and neck daily.', 'benefits' => 'Reduces shine, mattifies, deeply hydrates.'],
            ['id' => 12, 'name' => 'PDRN Pink Peptide Serum', 'brand' => 'Medicube', 'description' => 'A potent peptide serum for real results, enhancing skin elasticity and glow.', 'price' => 4500, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => '/images/skincare5.jpg', 'rating' => 4.9, 'reviews' => 156, 'ingredients' => 'PDRN (Sodium DNA) 1%, 5 Types Peptide Complex', 'how_to_use' => 'Apply a few drops after cleansing and toning.', 'benefits' => 'Improves skin elasticity, youthful glow.'],
            ['id' => 13, 'name' => 'Lactic Acid 10% + HA', 'brand' => 'The Ordinary', 'description' => 'High-strength lactic acid superficial peeling formulation.', 'price' => 1450, 'category' => 'skincare', 'skin_type' => 'oily', 'image' => '/images/skincare3.jpg', 'rating' => 4.7, 'reviews' => 670, 'ingredients' => 'Lactic Acid, Sodium Hyaluronate Crosspolymer', 'how_to_use' => 'Apply once per day, ideally in the PM.', 'benefits' => 'Exfoliates, evens skin tone, reduces texture.'],
            ['id' => 14, 'name' => 'Centella Hyalu-Cica Sleeping Pack', 'brand' => 'SKIN1004', 'description' => 'A soothing overnight sleeping pack with Centella to hydrate and comfort combination skin.', 'price' => 1900, 'category' => 'skincare', 'skin_type' => 'combination', 'image' => '/images/combination1.jpg', 'rating' => 4.8, 'reviews' => 184, 'ingredients' => 'Centella Asiatica, Hyaluronic Acid', 'how_to_use' => 'Apply an even layer as the final step of your evening skincare routine.', 'benefits' => 'Hydrates overnight and helps soothe the skin.'],
            ['id' => 15, 'name' => 'Sun Protect Moisturizing Cream SPF 50', 'brand' => 'Renew', 'description' => 'A moisturizing SPF 50 cream to help protect combination skin during the day.', 'price' => 2200, 'category' => 'skincare', 'skin_type' => 'combination', 'image' => '/images/combination3.jpg', 'rating' => 4.7, 'reviews' => 136, 'ingredients' => 'Broad-spectrum sunscreen filters, moisturizing emollients', 'how_to_use' => 'Apply generously to the face before sun exposure and reapply as needed.', 'benefits' => 'Provides sun protection with a moisturizing finish.'],
            ['id' => 16, 'name' => 'Hyaluronic Sunscreen Aqua Gel SPF 50', 'brand' => 'The Derma Co', 'description' => 'Lightweight, non-sticky SPF 50 sunscreen with hyaluronic acid for normal to oily skin.', 'price' => 1800, 'category' => 'skincare', 'skin_type' => 'combination', 'image' => '/images/combinatin2.jpg', 'rating' => 4.7, 'reviews' => 98, 'ingredients' => 'Hyaluronic Acid, Vitamin E', 'how_to_use' => 'Apply generously to face and neck before sun exposure. Reapply every two hours.', 'benefits' => 'Broad-spectrum SPF 50 protection with lightweight hydration.'],
        ];

        foreach ($products as $product) {
            if (! Product::query()->whereKey($product['id'])->exists()) {
                Product::query()->forceCreate($product);
            }
        }
    }
}
